name: Generate Snake Animation

on:
  schedule: # Jalankan otomatis tiap hari
    - cron: "0 0 * * *"
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake game from GitHub contribution grid
        uses: Platane/snk@v3
        with:
          github_user_name: andriyanooo
          outputs: dist/snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
